[Common]
; 這是獨立的時間選單項目
Times = 09:00 ~ 18:00 (全日),08:00 ~ 12:00 (上午),12:00 ~ 18:00 (下午)

[采邑]
Titles = 經理
Names = 程朝宗
CarPlates = RFV-7815
Reasons = EGATE 會議
Applicants = 翁振家 # 6241

[育冠資訊]
Titles = 課長
Names = 王小美
CarPlates = XYZ-9999
Reasons = 設備維護
Applicants = 王小美 # 5566
