[Common]
; 這是獨立的時間選單項目
Times = 09:00 ~ 18:00 (全日),08:00 ~ 12:00 (上午),12:00 ~ 18:00 (下午)

[采邑]
Titles = 經理
Names = 程朝宗
CarPlates = RFV-7815
Reasons = EGATE 會議
Applicants = 翁振家 # 6241

[博太]
Titles = 經理
Names = 張語恩
CarPlates = RFJ-9236
Reasons = GATE會議
Applicants = 翁振家 # 6241

[品輝]
Titles = 經理
Names = 林良能
CarPlates = 8800-TM
Reasons = GATE會議
Applicants = 翁振家 # 6241

[品 輝]
Titles = 經理
Names = 劉正皓
CarPlates = BJZ-9331
Reasons = GATE會議
Applicants = 翁振家 # 6241


劉正皓  BJZ-933
